apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: customer-api-binding
  namespace: nto-payment
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: customer-api
  parameters:
    adapter: nto-payment-service-mesh-adapter
    service: customer-service
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: inventory-api-binding
  namespace: nto-payment
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: inventory-api
  parameters:
    adapter: nto-payment-service-mesh-adapter
    service: inventory-service
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: order-api-binding
  namespace: nto-payment
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: order-api
  parameters:
    adapter: nto-payment-service-mesh-adapter
    service: order-service
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: payment-api-binding
  namespace: nto-payment
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: payment-api
  parameters:
    adapter: nto-payment-service-mesh-adapter
    service: payment-service
