apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: customer-api-binding
  namespace: <NAMESPACE>
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: asm-customer-api
  parameters:
    adapter: mythical-payment-service-mesh-adapter
    service: customer-service
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: inventory-api-binding
  namespace: <NAMESPACE>
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: asm-inventory-api
  parameters:
    adapter: mythical-payment-service-mesh-adapter
    service: inventory-service
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: order-api-binding
  namespace: <NAMESPACE>
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: asm-order-api
  parameters:
    adapter: mythical-payment-service-mesh-adapter
    service: order-service
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  # name will be used as resulting secret name if no secretName is specified under the spec section
  name: payment-api-binding
  namespace: <NAMESPACE>
  labels:
    service-mesh.mulesoft.com/kind: api-binding
spec:
  instanceRef:
    name: asm-payment-api
  parameters:
    adapter: mythical-payment-service-mesh-adapter
    service: payment-service
